# Generated by Django 4.0.2 on 2022-07-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reminder_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('reminder_time', models.DateField()),
                ('description', models.CharField(max_length=40)),
            ],
        ),
    ]
